### PR TITLE
remove optaplanner-bom

### PR DESCRIPTION
**Pull request by rgdoliveira**

### CODE REVIEW

**Comment by rgdoliveira** [comment]
should this be applied to main too?

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
I don't think we need to apply to main branch this change

**Comment by Ginxo** [comment]
> should this be applied to main too?

I don't think so :thinking:

**Review by Ginxo — APPROVED** [review]
LGTM

**Review by lampajr — APPROVED** [review]

**Pull request merged**
