### PR TITLE
BXMSPROD-57 merge rhpam and rhdm boms into rhba bom.

### PR DESCRIPTION
**Pull request by pszubiak**
Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>

### CODE REVIEW

**Comment by pszubiak** [comment]
@winklerm @cimbalek for some reason I can't set you as reviewers. We decided to merge RHDM and RHPAM boms. If I remember correctly it will affect tests too.

**Comment by winklerm** [comment]
@pszubiak thanks, looking into it. We need to update at least Maven repo tests to take it into account.

Does it also mean that we have only one Maven repository for both products? (Probably not needed, just checking.)

**Comment by mareknovotny** [comment]
@winklerm we need to have 2 zipped repositories, at least that is what I understand that we have 2 sets of binaries.

the only diff should be small though.

**Comment by pszubiak** [comment]
@mareknovotny @winklerm The idea is to have the same build procedure as for BxMS 6.4. It means that there will be one Brew build and two set of binaries from a different assembly code. The zipped repository will the same for RHPAM and RHDM.

It possible to have separate repository zips but they will be almost identical.

**Comment by winklerm** [comment]
For the record, I am all for having a single repository zip containing artifacts for both products :)

**Comment by mareknovotny** [comment]
+1

**Pull request merged**
